"""added role

Revision ID: 9c85146c4983
Revises: e05a56fb1280
Create Date: 2024-10-25 17:04:40.742715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c85146c4983'
down_revision: Union[str, None] = 'e05a56fb1280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', 'staff', name='userrole'), nullable=True))
    # ### end Alembic commands ###
    # Create the enum type
    userrole_enum = sa.Enum('admin', 'user', 'staff', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Add the new column to the users table
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', 'staff', name='userrole'), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###

    # Drop the enum type
    userrole_enum = sa.Enum(name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
